iso_name="higanveinos"
iso_label="HIGANVEINOS_$(date +%Y%m)"
iso_version="$(date +%Y.%m.%d)"
install_dir="arch"
buildmodes=('iso')
bootmodes=('bios.syslinux' 'uefi.grub')
arch="x86_64"
pacman_conf="pacman.conf"
airootfs_image_type="squashfs"
airootfs_image_tool_options=('-comp' 'zstd' '-Xcompression-level' '3')
file_permissions=(
  ["/etc/shadow"]="0:0:400"
  ["/etc/sudoers.d"]="0:0:750"
  ["/etc/sudoers.d/00-wheel-nopasswd"]="0:0:440"
  ["/home/higan"]="1000:1000:755"
  ["/home/higan/.profile"]="1000:1000:644"
  ["/usr/local/bin/higan-welcome"]="0:0:755"
  ["/usr/local/bin/pacman"]="0:0:755"
  ["/usr/local/bin/neofetch"]="0:0:755"
)
