[options]
HoldPkg     = pacman glibc
Architecture = auto
# Dedicated clean cache. Old host cache had corrupted packages.
CacheDir = /home/yahn/HiganveinOS/.cache/openrc-gui-pacman
SigLevel    = Never
LocalFileSigLevel = Optional

[system]
SigLevel = Never
Server = https://mirror.clarkson.edu/artix-linux/repos/system/os/$arch
Server = https://artix.sakamoto.pl/system/os/$arch
Server = https://mirror.pascalis.org/artix-linux/repos/system/os/$arch

[world]
SigLevel = Never
Server = https://mirror.clarkson.edu/artix-linux/repos/world/os/$arch
Server = https://artix.sakamoto.pl/world/os/$arch
Server = https://mirror.pascalis.org/artix-linux/repos/world/os/$arch

[galaxy]
SigLevel = Never
Server = https://mirror.clarkson.edu/artix-linux/repos/galaxy/os/$arch
Server = https://artix.sakamoto.pl/galaxy/os/$arch
Server = https://mirror.pascalis.org/artix-linux/repos/galaxy/os/$arch

[cachyos]
SigLevel = Never
Include = /etc/pacman.d/cachyos-mirrorlist

[core]
SigLevel = Never
Include = /etc/pacman.d/mirrorlist

[extra]
SigLevel = Never
Include = /etc/pacman.d/mirrorlist
