[options]
HoldPkg     = pacman glibc
Architecture = auto
SigLevel    = Never
LocalFileSigLevel = Optional

[cachyos]
SigLevel = Never
Include = /etc/pacman.d/cachyos-mirrorlist

[system]
SigLevel = Never
Server = https://mirrors.dotsrc.org/artix-linux/repos/system/os/$arch
Server = https://mirror.clarkson.edu/artix-linux/repos/system/os/$arch

[world]
SigLevel = Never
Server = https://mirrors.dotsrc.org/artix-linux/repos/world/os/$arch
Server = https://mirror.clarkson.edu/artix-linux/repos/world/os/$arch

[core]
SigLevel = Never
Include = /etc/pacman.d/mirrorlist

[extra]
SigLevel = Never
Include = /etc/pacman.d/mirrorlist
