# Limine Bootloader - HiganveinOS Frieren Theme
timeout: 5
interface_branding: H.V HiganveinOS
interface_branding_colour: ef4444
interface_help_colour: a1a1aa
interface_help_colour_bright: ef4444
default_entry: 1
wallpaper: boot():/limine-wallpaper.jpg
wallpaper_style: stretched
term_background: 9009090b
term_foreground: fafafa
term_margin: 64
term_margin_gradient: 4

/HiganveinOS (Default)
    protocol: linux
    kernel_path: boot():/vmlinuz-linux-cachyos
    kernel_cmdline: root=UUID=@ROOT_UUID@ rw quiet loglevel=3 splash
    module_path: boot():/initramfs-linux-cachyos.img

/HiganveinOS (Fallback Initramfs)
    protocol: linux
    kernel_path: boot():/vmlinuz-linux-cachyos
    kernel_cmdline: root=UUID=@ROOT_UUID@ rw
    module_path: boot():/initramfs-linux-cachyos-fallback.img
