# Limine Bootloader - HiganveinOS Theme
timeout: 5
interface_branding: H.V HiganveinOS
default_entry: 1

/HiganveinOS (Default)
    protocol: linux
    kernel_path: boot():/vmlinuz-linux-cachyos
    kernel_cmdline: root=UUID=@ROOT_UUID@ rw quiet loglevel=3 splash
    module_path: boot():/initramfs-linux-cachyos.img

/HiganveinOS (Fallback Initramfs)
    protocol: linux
    kernel_path: boot():/vmlinuz-linux-cachyos
    kernel_cmdline: root=UUID=@ROOT_UUID@ rw
    module_path: boot():/initramfs-linux-cachyos-fallback.img
